# Mandatory settings

name: Ninja Academy
paginate: 20
paginate_path: "/posts/page/:num/"
url: "http://ngninja.com/" # add site url http://example.com/
blog_theme: light # Or use dark

# Optional settings

discus_identifier: ng-ninja # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
rss_enabled: true # Change to false if not
google_analytics: UA-88588900-1 # google analytics tracking ID
social:
  dribbble: # Add your Dribbble handle
  facebook: ngrealninja # Add your Facebook handle
  github: # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  twitter: ng_real_ninja # Add your Twitter handle
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug